****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Tue Apr 25 16:58:59 CEST 2023
* Job name:             run_py_subp.sh
* Job id:               27323842
* User:                 namourou
* Account:              lsst
* Submit host:          cca004
* Partition:            htc
* Quality of service:   normal
* Nodelist:             ccwslurm0353
****************************************************************
DESC setup
GO1
Incorporation of magnitudes in AMICO catalog

Catalog loaded at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/DETECTIONS_DERIVED/ and will be saved in /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/

processing 8791
Healpix list : [8791, 8790, 8792, 8918, 8919, 9047] 
Now merging all input healpix files
Done. 
Incorporation of magnitudes
37029 0.1
76006 0.2
153960 0.4
231914 0.6
309868 0.8
387822 1.0
  GALID    FIELD_PROB ASSOC_ID ...       mag_y        mt_id_final
---------- ---------- -------- ... ------------------ -----------
1501502409 0.88584197      582 ... 23.209405557318703     2175824
1501504962 0.87811446      582 ... 22.096670967318662     2178247
1501700187  0.9775624      582 ...  24.33397295659214     2249545
1501706724  0.9506931      582 ... 22.785616838168337     2255677
1501706727 0.96409357      582 ... 23.377107918050566     2255680
There are : 0 galaxies which are not found inside input catalog
Program ran in : 296.0209095478058
Done.
G02
Reading amico files before merging
Reading tile =  8791
Reading clusters at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits 
Reading members at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/8791_map_associations_w_mag.fits 
Saving table at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/prepare_catalogs/read_amico_mb_subp.py", line 29, in <module>
    amico_cl_data = Table.read(cl_inpath)['ID', 'Xphys', 'Yphys', 'Zphys','LAMBSTAR', 'SN_NO_CLUSTER', 'SN', 'UID', 'TILE']  
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/raw_amico_cats/cosmoDC2_small_photoz_flexzboost_v1_iband/map_detections_refined_noBuffer_all_noDoubles_handFix.fits'
GO3
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Tue Apr 25 17:04:19 CEST 2023
Job informations can be found using these commands:
Accounting:
sacct -j 27323842
Efficiency:
seff 27323842
****************************************************************
